services:
  app:
    command: sh init.sh
    restart: always 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      NODE_ENV: ${ENVIRONMENT}
    env_file:
      - .env
